#define HAVE_MALLOC_H	1
#define HAVE_ALLOCA_H	1
#define HAVE_ALLOCA	1
#define HAVE_ATEXIT	1
#define HAVE_SIGACTION	1
#define HAVE_EXECINFO_H	1
#define HAVE_BACKTRACE	1
#define HAVE_MALLOC_STATS	1
#define HAVE_STDBOOL_H	1
#define HAVE_SETJMP_H	1
/* #undef HAVE_CLOCK_GETTIME */
#define LOGGER_DIRECTORY	"/tmp"
#ifdef NDEBUG
# define SNITCHASER_DEBUG_OFF
#endif

